### ISSUE TITLE
Cover menu at mobile devices

### ISSUE THREAD

**Issue by Polesovsky** [CodyHouse/responsive-sidebar-navigation#2]
![menu](https://user-images.githubusercontent.com/42830478/44835999-0c566480-ac36-11e8-8b34-5f82f0e4fc6b.png)

In case, when there are many content on page, menu didnt work correctly on mobile devices.
Menu do not cover all display, so users continue to scroll in page content after menu items.

I think, it is no ok, because content could be very long and menu items should be separate from other content

**Comment by Oscar-Raygoza** [comment]
I'll work very well on that

**Comment by sebastiano-guerriero** [comment]
Hi there! It's by design. The menu won't necessarily cover the whole viewport. If it doesn't, part of the content below is visible. Users should be used to menu items not covering the whole screen.
